# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'clms' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for clms
  pod 'AFNetworking', '~> 3.2.0'
  pod 'SDWebImage', '~> 4.3.3'
  pod 'YYModel', '~> 1.0.4'
  pod 'SVProgressHUD', '~> 2.2.5'

end
